# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0VHTUCQ4tVXUOmPjCOPDjnTW9z-DQ6O
"""

import os

if not os.path.exists('dashboard'):
    os.makedirs('dashboard')
    print("Folder 'dashboard' berhasil dibuat!")
else:
    print("Folder sudah ada.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard/dashboard.py
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import streamlit as st
# 
# sns.set(style='dark')
# 
# all_df = pd.read_csv("dashboard/main_data.csv")
# 
# st.title('Customer Demographics Dashboard 📊')
# 
# col1, col2 = st.columns(2)
# with col1:
#     st.metric("Total Pelanggan Unik", value=all_df.customer_unique_id.nunique())
# with col2:
#     st.metric("Total Negara Bagian", value=all_df.customer_state.nunique())
# 
# st.subheader("Top 5 Negara Bagian (States)")
# state_counts = all_df.groupby("customer_state").customer_unique_id.nunique().sort_values(ascending=False).head(5).reset_index()
# fig, ax = plt.subplots(figsize=(10, 5))
# sns.barplot(x="customer_unique_id", y="customer_state", data=state_counts, palette="viridis", ax=ax)
# st.pyplot(fig)
# 
# st.subheader("Top 10 Kota dengan Pelanggan Terbanyak")
# city_counts = all_df.groupby("customer_city").customer_unique_id.nunique().sort_values(ascending=False).head(10).reset_index()
# fig2, ax2 = plt.subplots(figsize=(10, 6))
# sns.barplot(x="customer_unique_id", y="customer_city", data=city_counts, palette="Blues_r", ax=ax2)
# st.pyplot(fig2)
# 
# st.subheader("Distribusi Pelanggan Berdasarkan Wilayah (Region)")
# region_counts = all_df.groupby("region").customer_unique_id.nunique().reset_index()
# fig3, ax3 = plt.subplots(figsize=(8, 8))
# ax3.pie(region_counts['customer_unique_id'], labels=region_counts['region'], autopct='%1.1f%%', startangle=140, colors=sns.color_palette("pastel"))
# st.pyplot(fig3)
# 
# st.caption('Copyright (c) 2026 - Proyek Analisis Data Pelanggan')

!pip install streamlit -q
!npm install -g localtunnel -q

print("IP Public Anda:")
!curl ipv4.icanhazip.com

!streamlit run dashboard/dashboard.py & npx localtunnel --port 8501